# Generated by Django 4.1.2 on 2022-10-24 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0003_alter_workout_options_profile_fullname_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 23)),
        ),
    ]
