# Generated by Django 4.0.5 on 2022-10-25 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0005_alter_profile_age_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 24)),
        ),
    ]
