# Generated by Django 4.1.2 on 2022-10-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
