# Generated by Django 4.0.5 on 2022-10-26 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_workout_fullname_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
    ]
